PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_api_keys` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`name` text,
	`start` text,
	`prefix` text,
	`key` text NOT NULL,
	`key_type` integer DEFAULT 1 NOT NULL,
	`identifier` text(16),
	`token` text,
	`allowed_ips` text,
	`memo` text,
	`last_used_at` integer,
	`expires_at` integer,
	`refill_interval` integer,
	`refill_amount` integer,
	`last_refill_at` integer,
	`enabled` integer DEFAULT true NOT NULL,
	`rate_limit_enabled` integer DEFAULT true NOT NULL,
	`rate_limit_time_window` integer,
	`rate_limit_max` integer,
	`request_count` integer DEFAULT 0 NOT NULL,
	`remaining` integer,
	`last_request` integer,
	`metadata` text,
	`permissions` text,
	`r_servers` integer DEFAULT 0 NOT NULL,
	`r_nodes` integer DEFAULT 0 NOT NULL,
	`r_allocations` integer DEFAULT 0 NOT NULL,
	`r_users` integer DEFAULT 0 NOT NULL,
	`r_locations` integer DEFAULT 0 NOT NULL,
	`r_nests` integer DEFAULT 0 NOT NULL,
	`r_eggs` integer DEFAULT 0 NOT NULL,
	`r_database_hosts` integer DEFAULT 0 NOT NULL,
	`r_server_databases` integer DEFAULT 0 NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
INSERT INTO `__new_api_keys`("id", "user_id", "name", "start", "prefix", "key", "key_type", "identifier", "token", "allowed_ips", "memo", "last_used_at", "expires_at", "refill_interval", "refill_amount", "last_refill_at", "enabled", "rate_limit_enabled", "rate_limit_time_window", "rate_limit_max", "request_count", "remaining", "last_request", "metadata", "permissions", "r_servers", "r_nodes", "r_allocations", "r_users", "r_locations", "r_nests", "r_eggs", "r_database_hosts", "r_server_databases", "created_at", "updated_at") 
SELECT 
	"id", 
	"user_id", 
	NULL as "name",
	NULL as "start",
	NULL as "prefix",
	COALESCE("token", '') as "key",
	"key_type", 
	"identifier", 
	"token", 
	"allowed_ips", 
	"memo", 
	"last_used_at", 
	"expires_at",
	NULL as "refill_interval",
	NULL as "refill_amount",
	NULL as "last_refill_at",
	1 as "enabled",
	1 as "rate_limit_enabled",
	NULL as "rate_limit_time_window",
	NULL as "rate_limit_max",
	0 as "request_count",
	NULL as "remaining",
	NULL as "last_request",
	NULL as "metadata",
	NULL as "permissions",
	"r_servers", 
	"r_nodes", 
	"r_allocations", 
	"r_users", 
	"r_locations", 
	"r_nests", 
	"r_eggs", 
	"r_database_hosts", 
	"r_server_databases", 
	"created_at", 
	"updated_at" 
FROM `api_keys`;--> statement-breakpoint
DROP TABLE `api_keys`;--> statement-breakpoint
ALTER TABLE `__new_api_keys` RENAME TO `api_keys`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE UNIQUE INDEX `api_keys_identifier_unique` ON `api_keys` (`identifier`) WHERE `identifier` IS NOT NULL;--> statement-breakpoint
CREATE INDEX `api_keys_user_id_index` ON `api_keys` (`user_id`);--> statement-breakpoint
CREATE INDEX `api_keys_key_index` ON `api_keys` (`key`);